---
title: "STAT394 Group 6 Report"
date: "2026-09-17"
output: pdf_document
indent: True
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# An Analysis on Tanaskovi´c et al. (2012)
### Group 6

\newpage

# Introduction

Serbia is located in Eastern Europe on the Balkan Peninsula. Many thermal springs can be found in Serbia. These waters are spread across different regions of the country, originating from various geological structures shaped by the region's complex geologic history. Waters from different geological origins and regions have different groundwater chemical properties due to different hydrochemical processes. (https://worldgeothermal.org/pdf/IGAstandard/WGC/2010/0164.pdf). 

Tanasković et al. (2012) statistically investigated the chemical and radioactive composition of spa water from different regions in Serbia. They took samples from spa waters from 30 different locations across Serbia, measuring 12 variables related to the hydrochemical processes and 6 related to radioactive isotopes. They analysed the data using multivariate statistical analysis to see if they could establish relationships and classify spa waters based on their chemical and radiological composition and geotectonic region. They analysed the data with a Pearson Correlation Matrix, Principal Component Analysis (PCA), Factor Analysis and Hierarchical Cluster Analysis (HCA). 

The 18 variables related to the spa water’s composition were loaded into four principal components, which contained 74.2% of the variation. Two of these were linked to variation in hydrochemical composition, and the other two related to radiological composition. The cluster analysis classified the waters into 4 main groups and 8 subgroups based on the similarity of water samples. From these results they were able to conclude that the geotectonic location of the spa water was a major factor in their composition (Tanasković et al. (2012)).
We aimed to undertake a similar analysis of the data, but as we only had access to the hydrochemical data of the samples and the referred radiological data is not publicly available, we were unable to replicate their analysis.
Based on the 12 hydrological data provided in the paper, our objective was to perform both a quantitative  and qualitative  analysis of the data in order to answer the following questions:

- Can you improve the paper’s results using Factor Analysis in terms of model quality with parsimony? 
- Are the groups identified by the dendrogram consistent with changes in the linkage and distance? 

Since we were working with a reduced dataset compared to the paper by Tanasković et al. (2012), our other objective was to compare our results with the ones they got and see if we can observe similar relationships between the geological origins of spa waters and their hydrochemical compositions, based solely on considering the chemical properties.

\newpage

# Data and Methodology  

## Data: 

The data used for our study were taken from Tanasković et al. (2012), Table 1, which includes 12 hydrochemical variables typically measured for water mineralogy assessment (https://www.cell.com/heliyon/fulltext/S2405-8440(23)04561-9), namely the outflowing temperature (T), pH, total solids content (TS), electrical conductivity (EC) and ions ($HCO_3^-$, $Ca^{2+}$, $Mg^{2+}{}$, $Na^+$, $K^+$, $Cl^-$, $SO_4^{2-}$ and $SiO_2$), obtained from 30 samples across different regions of Serbia. The data also include a labelling of Geological structure, which we use in our analysis. To complete our data, we have added an additional column, which labels the data based on the sampling location by different regions given by Tanasković et al. (2012) in Figure 1.

## Methods:

The multivariate analysis of the data was done with the freely available RStudio in the R software, developed locally at the University of Auckland in New Zealand (ref). 
Quantitative - Cathrine
For the qualitative analysis, the chemical data were studied using a Pearson Correlation Matrix of the data. Shapiro-Wilk’s tests were used to test whether each of our 12 variables individually followed a normal distribution with a significance level of 0.05. QQ-plots and Histograms were also used alongside these tests to check univariate normality for each of our variables. A Mardia’s test and a Henze-Zirkler test were carried out with a significance level of 0.05 to check whether our variables jointly followed a multivariate normal distribution. 

Mahalanobis distance was calculated from the multivariate mean and standard deviation to assess the consistency of the samples. For the validity of the Mahalanobis distance, we initially transformed most of the variables using individual box-cox transformations with differing lambda values. Results were also analysed with a pair plot for the different categories found by Mahalanobis distance.

Boxplots were used to show the chemical composition of the samples across the different geological structures and the different regions. In order to make the data more interpretable, PCA and FA were used to transform the data into a smaller dimension. Biplots and factor diagrams were used to facilitate the analysis of employing these dimensionality reduction techniques and interpret the structure of the data. Principal Components capture the maximum variance available in the dataset by transforming the data using eigenvalue decomposition. We use factor analysis with Varimax transformation to reduce the number of variable loadings per Factor and favour a reduced number of variables with higher loadings. This helps uncover psychological senses behind the data. For further analysis of the data, we also employ k-means clustering and HCA and compare our results with Tanaskovic et al.(2012).


\newpage

## Results and Discussion
